# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from config import v1_pb2 as config_dot_v1__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in config.v1_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConfigServiceStub:
    """============ 数据面服务（SDK 使用） ============

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetConfig = channel.unary_unary(
                '/config.v1.ConfigService/GetConfig',
                request_serializer=config_dot_v1__pb2.GetConfigRequest.SerializeToString,
                response_deserializer=config_dot_v1__pb2.ConfigSnapshot.FromString,
                _registered_method=True)
        self.GetItem = channel.unary_unary(
                '/config.v1.ConfigService/GetItem',
                request_serializer=config_dot_v1__pb2.GetItemRequest.SerializeToString,
                response_deserializer=config_dot_v1__pb2.ItemValue.FromString,
                _registered_method=True)
        self.Watch = channel.unary_stream(
                '/config.v1.ConfigService/Watch',
                request_serializer=config_dot_v1__pb2.WatchRequest.SerializeToString,
                response_deserializer=config_dot_v1__pb2.WatchEvent.FromString,
                _registered_method=True)
        self.ListMembers = channel.unary_unary(
                '/config.v1.ConfigService/ListMembers',
                request_serializer=config_dot_v1__pb2.ListMembersRequest.SerializeToString,
                response_deserializer=config_dot_v1__pb2.ListMembersResponse.FromString,
                _registered_method=True)


class ConfigServiceServicer:
    """============ 数据面服务（SDK 使用） ============

    """

    def GetConfig(self, request, context):
        """获取 (项目, 分支) 的配置快照；version=0 表示活动版本
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItem(self, request, context):
        """获取单个 item 值
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Watch(self, request, context):
        """订阅 (项目, 分支)：服务端流，仅在发布时推送事件
        after_version>0 时服务端先重放该版本之后的所有已发布事件
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMembers(self, request, context):
        """获取集群成员（用于 SDK 端点池动态更新）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConfigServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfig,
                    request_deserializer=config_dot_v1__pb2.GetConfigRequest.FromString,
                    response_serializer=config_dot_v1__pb2.ConfigSnapshot.SerializeToString,
            ),
            'GetItem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItem,
                    request_deserializer=config_dot_v1__pb2.GetItemRequest.FromString,
                    response_serializer=config_dot_v1__pb2.ItemValue.SerializeToString,
            ),
            'Watch': grpc.unary_stream_rpc_method_handler(
                    servicer.Watch,
                    request_deserializer=config_dot_v1__pb2.WatchRequest.FromString,
                    response_serializer=config_dot_v1__pb2.WatchEvent.SerializeToString,
            ),
            'ListMembers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMembers,
                    request_deserializer=config_dot_v1__pb2.ListMembersRequest.FromString,
                    response_serializer=config_dot_v1__pb2.ListMembersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'config.v1.ConfigService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('config.v1.ConfigService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConfigService:
    """============ 数据面服务（SDK 使用） ============

    """

    @staticmethod
    def GetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.v1.ConfigService/GetConfig',
            config_dot_v1__pb2.GetConfigRequest.SerializeToString,
            config_dot_v1__pb2.ConfigSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.v1.ConfigService/GetItem',
            config_dot_v1__pb2.GetItemRequest.SerializeToString,
            config_dot_v1__pb2.ItemValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Watch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/config.v1.ConfigService/Watch',
            config_dot_v1__pb2.WatchRequest.SerializeToString,
            config_dot_v1__pb2.WatchEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMembers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.v1.ConfigService/ListMembers',
            config_dot_v1__pb2.ListMembersRequest.SerializeToString,
            config_dot_v1__pb2.ListMembersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
