[package]
name = "dsh-jobs"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Defing config service - background jobs (module 11)"

[dependencies]
dsh-core = { path = "../dsh-core" }
dsh-crypto = { path = "../dsh-crypto" }
tokio = { workspace = true }
tracing = { workspace = true }
