// 分布式配置文档服务 —— 数据面契约 v1
// 依据：docs/design-v2.md（详细设计方案 v2.0）§5
// 语言：proto3 ｜ 包：config.v1
// 错误：RPC 失败返回 gRPC status；detail 中携带错误码（见 design-v2 §5.4）

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: config.v1.proto

package configv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValueType int32

const (
	ValueType_VALUE_TYPE_UNSPECIFIED ValueType = 0
	ValueType_STRING                 ValueType = 1
	ValueType_INT                    ValueType = 2
	ValueType_FLOAT                  ValueType = 3
	ValueType_BOOL                   ValueType = 4
	ValueType_JSON                   ValueType = 5 // 存规范化 JSON 文本
	ValueType_ARRAY                  ValueType = 6 // 字符串数组（元素类型约束见文档）
	ValueType_SECRET                 ValueType = 7 // 敏感项：数据面恒脱敏（masked=true），展示/导出脱敏
)

// Enum value maps for ValueType.
var (
	ValueType_name = map[int32]string{
		0: "VALUE_TYPE_UNSPECIFIED",
		1: "STRING",
		2: "INT",
		3: "FLOAT",
		4: "BOOL",
		5: "JSON",
		6: "ARRAY",
		7: "SECRET",
	}
	ValueType_value = map[string]int32{
		"VALUE_TYPE_UNSPECIFIED": 0,
		"STRING":                 1,
		"INT":                    2,
		"FLOAT":                  3,
		"BOOL":                   4,
		"JSON":                   5,
		"ARRAY":                  6,
		"SECRET":                 7,
	}
)

func (x ValueType) Enum() *ValueType {
	p := new(ValueType)
	*p = x
	return p
}

func (x ValueType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValueType) Descriptor() protoreflect.EnumDescriptor {
	return file_config_v1_proto_enumTypes[0].Descriptor()
}

func (ValueType) Type() protoreflect.EnumType {
	return &file_config_v1_proto_enumTypes[0]
}

func (x ValueType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValueType.Descriptor instead.
func (ValueType) EnumDescriptor() ([]byte, []int) {
	return file_config_v1_proto_rawDescGZIP(), []int{0}
}

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED EventType = 0
	EventType_VALUE_PUBLISH          EventType = 1 // 分支值发布
	EventType_STRUCTURE_PUBLISH      EventType = 2 // 结构发布（全分支同时生效）
	EventType_SHARED_CASCADE         EventType = 3 // 共享库发布导致的级联
	EventType_ROLLBACK               EventType = 4 // 回滚（内容=旧版本，版本号=新）
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "VALUE_PUBLISH",
		2: "STRUCTURE_PUBLISH",
		3: "SHARED_CASCADE",
		4: "ROLLBACK",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED": 0,
		"VALUE_PUBLISH":          1,
		"STRUCTURE_PUBLISH":      2,
		"SHARED_CASCADE":         3,
		"ROLLBACK":               4,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_config_v1_proto_enumTypes[1].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_config_v1_proto_enumTypes[1]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_config_v1_proto_rawDescGZIP(), []int{1}
}

type ChangeKind int32

const (
	ChangeKind_CHANGE_KIND_UNSPECIFIED ChangeKind = 0
	ChangeKind_UPSERT                  ChangeKind = 1 // 写入/更新
	ChangeKind_DELETE                  ChangeKind = 2 // 删除（结构发布中 item 被移除时）
)

// Enum value maps for ChangeKind.
var (
	ChangeKind_name = map[int32]string{
		0: "CHANGE_KIND_UNSPECIFIED",
		1: "UPSERT",
		2: "DELETE",
	}
	ChangeKind_value = map[string]int32{
		"CHANGE_KIND_UNSPECIFIED": 0,
		"UPSERT":                  1,
		"DELETE":                  2,
	}
)

func (x ChangeKind) Enum() *ChangeKind {
	p := new(ChangeKind)
	*p = x
	return p
}

func (x ChangeKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChangeKind) Descriptor() protoreflect.EnumDescriptor {
	return file_config_v1_proto_enumTypes[2].Descriptor()
}

func (ChangeKind) Type() protoreflect.EnumType {
	return &file_config_v1_proto_enumTypes[2]
}

func (x ChangeKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChangeKind.Descriptor instead.
func (ChangeKind) EnumDescriptor() ([]byte, []int) {
	return file_config_v1_proto_rawDescGZIP(), []int{2}
}

type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  ValueType              `protobuf:"varint,1,opt,name=type,proto3,enum=config.v1.ValueType" json:"type,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*Value_StrValue
	//	*Value_IntValue
	//	*Value_FloatValue
	//	*Value_BoolValue
	//	*Value_JsonValue
	//	*Value_ListValue
	Data isValue_Data `protobuf_oneof:"data"`
	// 管理面/导出场景：true 表示本值已脱敏（掩码），不应作为真实值使用
	Masked        bool `protobuf:"varint,8,opt,name=masked,proto3" json:"masked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_config_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_config_v1_proto_rawDescGZIP(), []int{0}
}

func (x *Value) GetType() ValueType {
	if x != nil {
		return x.Type
	}
	return ValueType_VALUE_TYPE_UNSPECIFIED
}

func (x *Value) GetData() isValue_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Value) GetStrValue() string {
	if x != nil {
		if x, ok := x.Data.(*Value_StrValue); ok {
			return x.StrValue
		}
	}
	return ""
}

func (x *Value) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Data.(*Value_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *Value) GetFloatValue() float64 {
	if x != nil {
		if x, ok := x.Data.(*Value_FloatValue); ok {
			return x.FloatValue
		}
	}
	return 0
}

func (x *Value) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Data.(*Value_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *Value) GetJsonValue() string {
	if x != nil {
		if x, ok := x.Data.(*Value_JsonValue); ok {
			return x.JsonValue
		}
	}
	return ""
}

func (x *Value) GetListValue() *StringList {
	if x != nil {
		if x, ok := x.Data.(*Value_ListValue); ok {
			return x.ListValue
		}
	}
	return nil
}

func (x *Value) GetMasked() bool {
	if x != nil {
		return x.Masked
	}
	return false
}

type isValue_Data interface {
	isValue_Data()
}

type Value_StrValue struct {
	StrValue string `protobuf:"bytes,2,opt,name=str_value,json=strValue,proto3,oneof"`
}

type Value_IntValue struct {
	IntValue int64 `protobuf:"varint,3,opt,name=int_value,json=intValue,proto3,oneof"`
}

type Value_FloatValue struct {
	FloatValue float64 `protobuf:"fixed64,4,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type Value_BoolValue struct {
	BoolValue bool `protobuf:"varint,5,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type Value_JsonValue struct {
	JsonValue string `protobuf:"bytes,6,opt,name=json_value,json=jsonValue,proto3,oneof"`
}

type Value_ListValue struct {
	ListValue *StringList `protobuf:"bytes,7,opt,name=list_value,json=listValue,proto3,oneof"`
}

func (*Value_StrValue) isValue_Data() {}

func (*Value_IntValue) isValue_Data() {}

func (*Value_FloatValue) isValue_Data() {}

func (*Value_BoolValue) isValue_Data() {}

func (*Value_JsonValue) isValue_Data() {}

func (*Value_ListValue) isValue_Data() {}

type StringList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringList) Reset() {
	*x = StringList{}
	mi := &file_config_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringList) ProtoMessage() {}

func (x *StringList) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringList.ProtoReflect.Descriptor instead.
func (*StringList) Descriptor() ([]byte, []int) {
	return file_config_v1_proto_rawDescGZIP(), []int{1}
}

func (x *StringList) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type GetConfigRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Project string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Branch  string                 `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	Version int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"` // 0 = 活动版本
	// G3/D26 灰度身份（向后兼容：旧客户端不传 = 空身份 = 稳定版，Q2）
	InstanceId    string            `protobuf:"bytes,4,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`                                                 // 稳定身份键（如 Pod 名/部署单元 ID；容器重建不变）
	Labels        map[string]string `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 灰度标签（如 zone=cn-north-1）；空 = 不参与标签匹配
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_config_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_proto_rawDescGZIP(), []int{2}
}

func (x *GetConfigRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *GetConfigRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *GetConfigRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetConfigRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *GetConfigRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type GroupData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         map[string]*Value      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupData) Reset() {
	*x = GroupData{}
	mi := &file_config_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupData) ProtoMessage() {}

func (x *GroupData) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupData.ProtoReflect.Descriptor instead.
func (*GroupData) Descriptor() ([]byte, []int) {
	return file_config_v1_proto_rawDescGZIP(), []int{3}
}

func (x *GroupData) GetItems() map[string]*Value {
	if x != nil {
		return x.Items
	}
	return nil
}

type ConfigSnapshot struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Project          string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Branch           string                 `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	Version          int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`                                           // 活动版本号（或请求的版本）
	StructureVersion int64                  `protobuf:"varint,4,opt,name=structure_version,json=structureVersion,proto3" json:"structure_version,omitempty"` // 结构版本号
	Groups           map[string]*GroupData  `protobuf:"bytes,5,rep,name=groups,proto3" json:"groups,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// G3/D27：灰度标记 + 解析出的版本号（客户端可见自己在哪个版本）
	Gray            bool  `protobuf:"varint,6,opt,name=gray,proto3" json:"gray,omitempty"`                                              // true = 本次返回灰度快照内容
	ResolvedVersion int64 `protobuf:"varint,7,opt,name=resolved_version,json=resolvedVersion,proto3" json:"resolved_version,omitempty"` // 服务端按身份 resolve 的版本号（稳定=active；灰度=gray_seq）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConfigSnapshot) Reset() {
	*x = ConfigSnapshot{}
	mi := &file_config_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSnapshot) ProtoMessage() {}

func (x *ConfigSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSnapshot.ProtoReflect.Descriptor instead.
func (*ConfigSnapshot) Descriptor() ([]byte, []int) {
	return file_config_v1_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigSnapshot) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *ConfigSnapshot) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *ConfigSnapshot) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ConfigSnapshot) GetStructureVersion() int64 {
	if x != nil {
		return x.StructureVersion
	}
	return 0
}

func (x *ConfigSnapshot) GetGroups() map[string]*GroupData {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *ConfigSnapshot) GetGray() bool {
	if x != nil {
		return x.Gray
	}
	return false
}

func (x *ConfigSnapshot) GetResolvedVersion() int64 {
	if x != nil {
		return x.ResolvedVersion
	}
	return 0
}

type GetItemRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Project string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Branch  string                 `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	Group   string                 `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	Key     string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	Version int64                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"` // 0 = 活动版本
	// G3/D26 灰度身份（Q6：get_item 必须同样 resolve）
	InstanceId    string            `protobuf:"bytes,6,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Labels        map[string]string `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemRequest) Reset() {
	*x = GetItemRequest{}
	mi := &file_config_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemRequest) ProtoMessage() {}

func (x *GetItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemRequest.ProtoReflect.Descriptor instead.
func (*GetItemRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_proto_rawDescGZIP(), []int{5}
}

func (x *GetItemRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *GetItemRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *GetItemRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *GetItemRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetItemRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetItemRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *GetItemRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type ItemValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         *Value                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemValue) Reset() {
	*x = ItemValue{}
	mi := &file_config_v1_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemValue) ProtoMessage() {}

func (x *ItemValue) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemValue.ProtoReflect.Descriptor instead.
func (*ItemValue) Descriptor() ([]byte, []int) {
	return file_config_v1_proto_rawDescGZIP(), []int{6}
}

func (x *ItemValue) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ItemValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ItemValue) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Branch        string                 `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	AfterVersion  int64                  `protobuf:"varint,3,opt,name=after_version,json=afterVersion,proto3" json:"after_version,omitempty"` // 断线续传起点（0 = 从当前活动版本开始）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_config_v1_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_proto_rawDescGZIP(), []int{7}
}

func (x *WatchRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *WatchRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *WatchRequest) GetAfterVersion() int64 {
	if x != nil {
		return x.AfterVersion
	}
	return 0
}

type Change struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Kind          ChangeKind             `protobuf:"varint,3,opt,name=kind,proto3,enum=config.v1.ChangeKind" json:"kind,omitempty"`
	NewValue      *Value                 `protobuf:"bytes,4,opt,name=new_value,json=newValue,proto3" json:"new_value,omitempty"` // DELETE 时为空
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Change) Reset() {
	*x = Change{}
	mi := &file_config_v1_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Change) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Change) ProtoMessage() {}

func (x *Change) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Change.ProtoReflect.Descriptor instead.
func (*Change) Descriptor() ([]byte, []int) {
	return file_config_v1_proto_rawDescGZIP(), []int{8}
}

func (x *Change) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Change) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Change) GetKind() ChangeKind {
	if x != nil {
		return x.Kind
	}
	return ChangeKind_CHANGE_KIND_UNSPECIFIED
}

func (x *Change) GetNewValue() *Value {
	if x != nil {
		return x.NewValue
	}
	return nil
}

type WatchEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 事件相关版本号：普通事件 = 发布产生的新版本号（(项目,分支) 内单调递增）；
	// 灰度事件（gray=true）可携带 ≤ 客户端 last 的版本（如 abort 的回落 active）——
	// SDK 契约：gray 事件永不按版本过滤（见 gray 字段注释）。
	Version          int64     `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Type             EventType `protobuf:"varint,2,opt,name=type,proto3,enum=config.v1.EventType" json:"type,omitempty"`
	StructureVersion int64     `protobuf:"varint,3,opt,name=structure_version,json=structureVersion,proto3" json:"structure_version,omitempty"` // 本次事件时的结构版本
	Comment          string    `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`                                            // 发布备注
	RequestId        string    `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`                       // 幂等键（与发布请求一致，便于对账）
	Changes          []*Change `protobuf:"bytes,6,rep,name=changes,proto3" json:"changes,omitempty"`
	// 服务端认为客户端缓存可能已失效（慢消费者/起点被裁剪前），客户端应重拉全量
	SnapshotRequired bool `protobuf:"varint,7,opt,name=snapshot_required,json=snapshotRequired,proto3" json:"snapshot_required,omitempty"`
	// G3/D25 方案 b：gray=true 事件永不按版本过滤（SDK 契约：收到 gray 事件无条件重拉全量）
	Gray          bool `protobuf:"varint,8,opt,name=gray,proto3" json:"gray,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchEvent) Reset() {
	*x = WatchEvent{}
	mi := &file_config_v1_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEvent) ProtoMessage() {}

func (x *WatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEvent.ProtoReflect.Descriptor instead.
func (*WatchEvent) Descriptor() ([]byte, []int) {
	return file_config_v1_proto_rawDescGZIP(), []int{9}
}

func (x *WatchEvent) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *WatchEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *WatchEvent) GetStructureVersion() int64 {
	if x != nil {
		return x.StructureVersion
	}
	return 0
}

func (x *WatchEvent) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *WatchEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *WatchEvent) GetChanges() []*Change {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *WatchEvent) GetSnapshotRequired() bool {
	if x != nil {
		return x.SnapshotRequired
	}
	return false
}

func (x *WatchEvent) GetGray() bool {
	if x != nil {
		return x.Gray
	}
	return false
}

type ListMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersRequest) Reset() {
	*x = ListMembersRequest{}
	mi := &file_config_v1_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersRequest) ProtoMessage() {}

func (x *ListMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersRequest.ProtoReflect.Descriptor instead.
func (*ListMembersRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_proto_rawDescGZIP(), []int{10}
}

type Member struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	GrpcAddr       string                 `protobuf:"bytes,2,opt,name=grpc_addr,json=grpcAddr,proto3" json:"grpc_addr,omitempty"`
	HttpAddr       string                 `protobuf:"bytes,3,opt,name=http_addr,json=httpAddr,proto3" json:"http_addr,omitempty"`
	IsLeader       bool                   `protobuf:"varint,4,opt,name=is_leader,json=isLeader,proto3" json:"is_leader,omitempty"`
	IsVoter        bool                   `protobuf:"varint,5,opt,name=is_voter,json=isVoter,proto3" json:"is_voter,omitempty"`
	CommittedIndex int64                  `protobuf:"varint,6,opt,name=committed_index,json=committedIndex,proto3" json:"committed_index,omitempty"` // 用于选择最新节点
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_config_v1_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_config_v1_proto_rawDescGZIP(), []int{11}
}

func (x *Member) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Member) GetGrpcAddr() string {
	if x != nil {
		return x.GrpcAddr
	}
	return ""
}

func (x *Member) GetHttpAddr() string {
	if x != nil {
		return x.HttpAddr
	}
	return ""
}

func (x *Member) GetIsLeader() bool {
	if x != nil {
		return x.IsLeader
	}
	return false
}

func (x *Member) GetIsVoter() bool {
	if x != nil {
		return x.IsVoter
	}
	return false
}

func (x *Member) GetCommittedIndex() int64 {
	if x != nil {
		return x.CommittedIndex
	}
	return 0
}

type ListMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*Member              `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersResponse) Reset() {
	*x = ListMembersResponse{}
	mi := &file_config_v1_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersResponse) ProtoMessage() {}

func (x *ListMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersResponse.ProtoReflect.Descriptor instead.
func (*ListMembersResponse) Descriptor() ([]byte, []int) {
	return file_config_v1_proto_rawDescGZIP(), []int{12}
}

func (x *ListMembersResponse) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

var File_config_v1_proto protoreflect.FileDescriptor

const file_config_v1_proto_rawDesc = "" +
	"\n" +
	"\x0fconfig.v1.proto\x12\tconfig.v1\"\xac\x02\n" +
	"\x05Value\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.config.v1.ValueTypeR\x04type\x12\x1d\n" +
	"\tstr_value\x18\x02 \x01(\tH\x00R\bstrValue\x12\x1d\n" +
	"\tint_value\x18\x03 \x01(\x03H\x00R\bintValue\x12!\n" +
	"\vfloat_value\x18\x04 \x01(\x01H\x00R\n" +
	"floatValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x05 \x01(\bH\x00R\tboolValue\x12\x1f\n" +
	"\n" +
	"json_value\x18\x06 \x01(\tH\x00R\tjsonValue\x126\n" +
	"\n" +
	"list_value\x18\a \x01(\v2\x15.config.v1.StringListH\x00R\tlistValue\x12\x16\n" +
	"\x06masked\x18\b \x01(\bR\x06maskedB\x06\n" +
	"\x04data\"$\n" +
	"\n" +
	"StringList\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\xfb\x01\n" +
	"\x10GetConfigRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\x12\x1f\n" +
	"\vinstance_id\x18\x04 \x01(\tR\n" +
	"instanceId\x12?\n" +
	"\x06labels\x18\x05 \x03(\v2'.config.v1.GetConfigRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8e\x01\n" +
	"\tGroupData\x125\n" +
	"\x05items\x18\x01 \x03(\v2\x1f.config.v1.GroupData.ItemsEntryR\x05items\x1aJ\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.config.v1.ValueR\x05value:\x028\x01\"\xd8\x02\n" +
	"\x0eConfigSnapshot\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\x12+\n" +
	"\x11structure_version\x18\x04 \x01(\x03R\x10structureVersion\x12=\n" +
	"\x06groups\x18\x05 \x03(\v2%.config.v1.ConfigSnapshot.GroupsEntryR\x06groups\x12\x12\n" +
	"\x04gray\x18\x06 \x01(\bR\x04gray\x12)\n" +
	"\x10resolved_version\x18\a \x01(\x03R\x0fresolvedVersion\x1aO\n" +
	"\vGroupsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.config.v1.GroupDataR\x05value:\x028\x01\"\x9f\x02\n" +
	"\x0eGetItemRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\x12\x14\n" +
	"\x05group\x18\x03 \x01(\tR\x05group\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x03R\aversion\x12\x1f\n" +
	"\vinstance_id\x18\x06 \x01(\tR\n" +
	"instanceId\x12=\n" +
	"\x06labels\x18\a \x03(\v2%.config.v1.GetItemRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"[\n" +
	"\tItemValue\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x03 \x01(\v2\x10.config.v1.ValueR\x05value\"e\n" +
	"\fWatchRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\x12#\n" +
	"\rafter_version\x18\x03 \x01(\x03R\fafterVersion\"\x8a\x01\n" +
	"\x06Change\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12)\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x15.config.v1.ChangeKindR\x04kind\x12-\n" +
	"\tnew_value\x18\x04 \x01(\v2\x10.config.v1.ValueR\bnewValue\"\xa4\x02\n" +
	"\n" +
	"WatchEvent\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12(\n" +
	"\x04type\x18\x02 \x01(\x0e2\x14.config.v1.EventTypeR\x04type\x12+\n" +
	"\x11structure_version\x18\x03 \x01(\x03R\x10structureVersion\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\x12+\n" +
	"\achanges\x18\x06 \x03(\v2\x11.config.v1.ChangeR\achanges\x12+\n" +
	"\x11snapshot_required\x18\a \x01(\bR\x10snapshotRequired\x12\x12\n" +
	"\x04gray\x18\b \x01(\bR\x04gray\"\x14\n" +
	"\x12ListMembersRequest\"\xbc\x01\n" +
	"\x06Member\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tgrpc_addr\x18\x02 \x01(\tR\bgrpcAddr\x12\x1b\n" +
	"\thttp_addr\x18\x03 \x01(\tR\bhttpAddr\x12\x1b\n" +
	"\tis_leader\x18\x04 \x01(\bR\bisLeader\x12\x19\n" +
	"\bis_voter\x18\x05 \x01(\bR\aisVoter\x12'\n" +
	"\x0fcommitted_index\x18\x06 \x01(\x03R\x0ecommittedIndex\"B\n" +
	"\x13ListMembersResponse\x12+\n" +
	"\amembers\x18\x01 \x03(\v2\x11.config.v1.MemberR\amembers*r\n" +
	"\tValueType\x12\x1a\n" +
	"\x16VALUE_TYPE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06STRING\x10\x01\x12\a\n" +
	"\x03INT\x10\x02\x12\t\n" +
	"\x05FLOAT\x10\x03\x12\b\n" +
	"\x04BOOL\x10\x04\x12\b\n" +
	"\x04JSON\x10\x05\x12\t\n" +
	"\x05ARRAY\x10\x06\x12\n" +
	"\n" +
	"\x06SECRET\x10\a*s\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rVALUE_PUBLISH\x10\x01\x12\x15\n" +
	"\x11STRUCTURE_PUBLISH\x10\x02\x12\x12\n" +
	"\x0eSHARED_CASCADE\x10\x03\x12\f\n" +
	"\bROLLBACK\x10\x04*A\n" +
	"\n" +
	"ChangeKind\x12\x1b\n" +
	"\x17CHANGE_KIND_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06UPSERT\x10\x01\x12\n" +
	"\n" +
	"\x06DELETE\x10\x022\x99\x02\n" +
	"\rConfigService\x12C\n" +
	"\tGetConfig\x12\x1b.config.v1.GetConfigRequest\x1a\x19.config.v1.ConfigSnapshot\x12:\n" +
	"\aGetItem\x12\x19.config.v1.GetItemRequest\x1a\x14.config.v1.ItemValue\x129\n" +
	"\x05Watch\x12\x17.config.v1.WatchRequest\x1a\x15.config.v1.WatchEvent0\x01\x12L\n" +
	"\vListMembers\x12\x1d.config.v1.ListMembersRequest\x1a\x1e.config.v1.ListMembersResponseB'\n" +
	"\x11com.dsh.config.v1Z\x12config/v1;configv1b\x06proto3"

var (
	file_config_v1_proto_rawDescOnce sync.Once
	file_config_v1_proto_rawDescData []byte
)

func file_config_v1_proto_rawDescGZIP() []byte {
	file_config_v1_proto_rawDescOnce.Do(func() {
		file_config_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_v1_proto_rawDesc), len(file_config_v1_proto_rawDesc)))
	})
	return file_config_v1_proto_rawDescData
}

var file_config_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_config_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_config_v1_proto_goTypes = []any{
	(ValueType)(0),              // 0: config.v1.ValueType
	(EventType)(0),              // 1: config.v1.EventType
	(ChangeKind)(0),             // 2: config.v1.ChangeKind
	(*Value)(nil),               // 3: config.v1.Value
	(*StringList)(nil),          // 4: config.v1.StringList
	(*GetConfigRequest)(nil),    // 5: config.v1.GetConfigRequest
	(*GroupData)(nil),           // 6: config.v1.GroupData
	(*ConfigSnapshot)(nil),      // 7: config.v1.ConfigSnapshot
	(*GetItemRequest)(nil),      // 8: config.v1.GetItemRequest
	(*ItemValue)(nil),           // 9: config.v1.ItemValue
	(*WatchRequest)(nil),        // 10: config.v1.WatchRequest
	(*Change)(nil),              // 11: config.v1.Change
	(*WatchEvent)(nil),          // 12: config.v1.WatchEvent
	(*ListMembersRequest)(nil),  // 13: config.v1.ListMembersRequest
	(*Member)(nil),              // 14: config.v1.Member
	(*ListMembersResponse)(nil), // 15: config.v1.ListMembersResponse
	nil,                         // 16: config.v1.GetConfigRequest.LabelsEntry
	nil,                         // 17: config.v1.GroupData.ItemsEntry
	nil,                         // 18: config.v1.ConfigSnapshot.GroupsEntry
	nil,                         // 19: config.v1.GetItemRequest.LabelsEntry
}
var file_config_v1_proto_depIdxs = []int32{
	0,  // 0: config.v1.Value.type:type_name -> config.v1.ValueType
	4,  // 1: config.v1.Value.list_value:type_name -> config.v1.StringList
	16, // 2: config.v1.GetConfigRequest.labels:type_name -> config.v1.GetConfigRequest.LabelsEntry
	17, // 3: config.v1.GroupData.items:type_name -> config.v1.GroupData.ItemsEntry
	18, // 4: config.v1.ConfigSnapshot.groups:type_name -> config.v1.ConfigSnapshot.GroupsEntry
	19, // 5: config.v1.GetItemRequest.labels:type_name -> config.v1.GetItemRequest.LabelsEntry
	3,  // 6: config.v1.ItemValue.value:type_name -> config.v1.Value
	2,  // 7: config.v1.Change.kind:type_name -> config.v1.ChangeKind
	3,  // 8: config.v1.Change.new_value:type_name -> config.v1.Value
	1,  // 9: config.v1.WatchEvent.type:type_name -> config.v1.EventType
	11, // 10: config.v1.WatchEvent.changes:type_name -> config.v1.Change
	14, // 11: config.v1.ListMembersResponse.members:type_name -> config.v1.Member
	3,  // 12: config.v1.GroupData.ItemsEntry.value:type_name -> config.v1.Value
	6,  // 13: config.v1.ConfigSnapshot.GroupsEntry.value:type_name -> config.v1.GroupData
	5,  // 14: config.v1.ConfigService.GetConfig:input_type -> config.v1.GetConfigRequest
	8,  // 15: config.v1.ConfigService.GetItem:input_type -> config.v1.GetItemRequest
	10, // 16: config.v1.ConfigService.Watch:input_type -> config.v1.WatchRequest
	13, // 17: config.v1.ConfigService.ListMembers:input_type -> config.v1.ListMembersRequest
	7,  // 18: config.v1.ConfigService.GetConfig:output_type -> config.v1.ConfigSnapshot
	9,  // 19: config.v1.ConfigService.GetItem:output_type -> config.v1.ItemValue
	12, // 20: config.v1.ConfigService.Watch:output_type -> config.v1.WatchEvent
	15, // 21: config.v1.ConfigService.ListMembers:output_type -> config.v1.ListMembersResponse
	18, // [18:22] is the sub-list for method output_type
	14, // [14:18] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_config_v1_proto_init() }
func file_config_v1_proto_init() {
	if File_config_v1_proto != nil {
		return
	}
	file_config_v1_proto_msgTypes[0].OneofWrappers = []any{
		(*Value_StrValue)(nil),
		(*Value_IntValue)(nil),
		(*Value_FloatValue)(nil),
		(*Value_BoolValue)(nil),
		(*Value_JsonValue)(nil),
		(*Value_ListValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_v1_proto_rawDesc), len(file_config_v1_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_config_v1_proto_goTypes,
		DependencyIndexes: file_config_v1_proto_depIdxs,
		EnumInfos:         file_config_v1_proto_enumTypes,
		MessageInfos:      file_config_v1_proto_msgTypes,
	}.Build()
	File_config_v1_proto = out.File
	file_config_v1_proto_goTypes = nil
	file_config_v1_proto_depIdxs = nil
}
